pub const NAMES: [&str; 20] = [
    "Mutant",
    "Claws",
    "Net Fighter",
    "Brawler",
    "Assasin",
    "Medic",
    "Officer",
    "Scout",
    "Juggernaut",
    "Gauss Cannon",
    "Hornet",
    "Guard",
    "Hunter-killer",
    "The Clown",
    "Commando",
    "Annihilator",
    "Runner",
    "Ganger",
    "Gladiator",
    "Thug",
];
