name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.68.0
    - uses: actions/checkout@master
    - name: Run tests
      env:
        CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      run: cargo test --verbose