name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@1.68.0
        with:
          args: CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo test